name: Build linux-x86_64 dependencies

on:
  schedule:
    # Runs every 24 hours
    - cron: "0 */24 * * *"
  workflow_dispatch:
 
# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-linux-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-3.3.0
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Print environment
        run: |
          printenv
      - name: Install `LuaFileSystem` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luafilesystem
          luarocks --verbose pack luafilesystem
      - name: Install `luarocks-build-rust-mlua` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luarocks-build-rust-mlua
          luarocks --verbose pack luarocks-build-rust-mlua
      - name: Install TOML Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml
          luarocks --verbose pack toml
      - name: Install `toml-edit` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml-edit
          luarocks --verbose pack toml-edit
      - name: Install `fzy` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install fzy
          luarocks --verbose pack fzy
      - name: Install `jsregexp` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install jsregexp
          luarocks --verbose pack jsregexp
      - name: Install `tree-sitter-orgmode` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-orgmode
          luarocks --verbose pack tree-sitter-orgmode
      # - name: Install `tree-sitter-norg` Package
      #   run: |
      #     luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg
      #     luarocks --verbose pack tree-sitter-norg
      # - name: Install `tree-sitter-norg-meta` Package
      #   run: |
      #     luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg-meta
      #     luarocks --verbose pack tree-sitter-norg-meta
      # - name: Install `luarocks-build-treesitter-parser` Package
      #   run: |
      #     luarocks --verbose --local --lua-version=5.1 install luarocks-build-treesitter-parser
      # - name: Get tree-sitter-parsers.json
      #   uses: actions/checkout@v4
      #   with: 
      #     repository: nvim-neorocks/nurr
      #     sparse-checkout: |
      #       tree-sitter-parsers.json
      #     path: nurr
      # - name: Install tree-sitter parsers
      #   run: |
      #     # Filter out parsers that need their sources generated
      #     # We might want to consider adding those too
      #     langs=$(jq -r '.parsers[] | select((.install_info.requires_generate_from_grammar // false) == false) | .lang' nurr/tree-sitter-parsers.json)
      #     for lang in $langs; do
      #       rm "tree-sitter-$lang-scm-1.linux-x86_64.rock" || true
      #       luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
      #         && luarocks pack "tree-sitter-$lang" || echo "Failed to pack tree-sitter-$lang"
      #     done
      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .
      - name: commit-linux-x86_64
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update linux-x86_64 build artifacts"
          file_pattern: "*.rock manifest* index.html"
