name: Build macosx-x86_64 dependencies

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build macosx-aarch64 dependencies"]
    branches: [main]
    types: 
      - completed

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-macosx-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Clang 16
        run: brew install llvm@16
      - name: Export path
        run: |
          export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"
      - name: Install Rust Toolchain (macos)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-C link-arg=-undefined -C link-arg=dynamic_lookup"
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Print environment
        run: |
          printenv
      - name: Install `LuaFileSystem` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luafilesystem
          luarocks --verbose pack luafilesystem
      - name: Install `luarocks-build-rust-mlua` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luarocks-build-rust-mlua
          luarocks --verbose pack luarocks-build-rust-mlua
      - name: Install TOML Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml
          luarocks --verbose pack toml
      - name: Install `toml-edit` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml-edit
          luarocks --verbose pack toml-edit
      - name: Install `fzy` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install fzy
          luarocks --verbose pack fzy
      - name: Install `tree-sitter-orgmode` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-orgmode
          luarocks --verbose pack tree-sitter-orgmode
      - name: "[HACK]: Set default compiler flags for MacOS systems"
        run: |
          luarocks config --lua-version=5.1 --scope=system -- variables.LIBFLAG "-bundle -undefined dynamic_lookup -all_load -std=c++11"
      - name: Install `tree-sitter-norg` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg
          luarocks --verbose pack tree-sitter-norg
      - name: Install `tree-sitter-norg-meta` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg-meta
          luarocks --verbose pack tree-sitter-norg-meta
      # - name: Install `luarocks-build-treesitter-parser` Package
      #   run: |
      #     luarocks --verbose --local --lua-version=5.1 install luarocks-build-treesitter-parser
      # - name: Get tree-sitter-parsers.json
      #   uses: actions/checkout@v4
      #   with: 
      #     repository: nvim-neorocks/nurr
      #     sparse-checkout: |
      #       tree-sitter-parsers.json
      #     path: nurr
      # - name: Install tree-sitter parsers
      #   run: |
      #     # Filter out parsers that need their sources generated
      #     # We might want to consider adding those too
      #     langs=$(jq -r '.parsers[] | select((.install_info.requires_generate_from_grammar // false) == false) | .lang' nurr/tree-sitter-parsers.json)
      #     for lang in $langs; do
      #       rm "tree-sitter-$lang-scm-1.macosx-x86_64.rock" || true
      #       luarocks --local --lua-version=5.1 install "tree-sitter-$lang" \
      #         && luarocks pack "tree-sitter-$lang" || echo "Failed to pack tree-sitter-$lang"
      #     done
      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .
      - name: commit-macosx-x86_64
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update macosx-x86_64 build artifacts"
          file_pattern: "*.rock manifest* index.html"
