name: Build `luarocks-rust-build-mlua` Dependency

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - host: ubuntu-20.04
          - host: windows-2019
          - host: macos-11
    steps:
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Install `luarocks-build-rust-mlua` Package
        run: |
          luarocks --local --lua-version=5.1 install luarocks-build-rust-mlua
          luarocks pack luarocks-build-rust-mlua
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update build artifacts"
          file_pattern: '*.rock'
