name: Build macosx-x86_64 dependencies

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build macosx-aarch64 dependencies"]
    branches: [main]
    types: 
      - completed

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-macosx-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install Rust Toolchain (macos)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-C link-arg=-undefined -C link-arg=dynamic_lookup"
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Print environment
        run: |
          printenv
      - name: Install `luarocks-build-rust-mlua` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luarocks-build-rust-mlua
          luarocks --verbose pack luarocks-build-rust-mlua
      - name: Install TOML Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml
          luarocks --verbose pack toml
      - name: Install `toml-edit` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml-edit
          luarocks --verbose pack toml-edit
      - name: Install `fzy` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install fzy
          luarocks --verbose pack fzy
      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .
      - name: commit-macosx-x86_64
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update macosx-x86_64 build artifacts"
          file_pattern: "*.rock manifest* index.html"
