name: Build win32-x86_64 dependencies

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build macosx-x86_64 dependencies"]
    branches: [main]
    types: 
      - completed

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-win32-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install tree-sitter CLI
        uses: baptiste0928/cargo-install@v3
        with:
          crate: tree-sitter-cli

      - name: Install Scoop
        uses: MinoruSekine/setup-scoop@v4

      - name: Add rocks-scoop bucket
        run: |
          scoop bucket add neorocks-scoop https://github.com/nvim-neorocks/rocks-scoop.git

      - name: Install luarocks
        run: |
          scoop install neorocks-scoop/luarocks

      - name: Print environment
        run: |
          printenv
      - name: Install `fzy` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install fzy
          luarocks --verbose pack fzy
        if: always()
      - name: Install `LuaFileSystem` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luafilesystem
          luarocks --verbose pack luafilesystem
        if: always()
      - name: Install `luarocks-build-rust-mlua` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luarocks-build-rust-mlua
          luarocks --verbose pack luarocks-build-rust-mlua
        if: always()
      - name: Install TOML Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml
          luarocks --verbose pack toml
        if: always()
      - name: Install `toml-edit` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml-edit
          luarocks --verbose pack toml-edit
        if: always()
      - name: Install `jsregexp` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install jsregexp
          luarocks --verbose pack jsregexp
      - name: Install `curl`
        run: |
          scoop install curl
        if: always()
      - name: Install `lua-curl` Package
        run: ./scripts/pack_binary_rock.lua lua-curl win32-x86_64
        if: always()

      - name: Install `tree-sitter-orgmode` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-orgmode
          luarocks --verbose pack tree-sitter-orgmode
        if: always()
      - name: Install `tree-sitter-norg` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg
          luarocks --verbose pack tree-sitter-norg
        if: always()
      - name: Install `tree-sitter-norg-meta` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install tree-sitter-norg-meta
          luarocks --verbose pack tree-sitter-norg-meta
        if: always()
      - name: Get tree-sitter-parsers.json
        uses: actions/checkout@v4
        with: 
          repository: nvim-neorocks/nurr
          sparse-checkout: |
            tree-sitter-parsers.json
          path: nurr
        if: always()
      - name: Install tree-sitter parsers
        run: |
          $langs = (jq -r '.parsers[] | .lang' nurr/tree-sitter-parsers.json).Replace("`r","")
          foreach ($lang in $langs) {
            luarocks --local --lua-version=5.1 install "tree-sitter-$lang"
            luarocks pack "tree-sitter-$lang"
          }
        if: always()
      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .
        if: always()
      - name: commit-win32-x86_64
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update win32-x86_64 build artifacts"
          file_pattern: "*.win32-x86_64.rock *.all.rock manifest* index.html"
        if: always()
