name: Build win32-x86_64 dependencies

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build macosx-x86_64 dependencies"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest
      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Print environment
        run: |
          printenv
      - name: Install `luarocks-build-rust-mlua` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install luarocks-build-rust-mlua
          luarocks --verbose pack luarocks-build-rust-mlua
      - name: Install TOML Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml
          luarocks --verbose pack toml
      - name: Install `toml-edit` Package
        run: |
          luarocks --verbose --local --lua-version=5.1 install toml-edit
          luarocks --verbose pack toml-edit
      - name: Regenerate Manifests and HTML
        run: luarocks-admin make-manifest --lua-version=5.1 .
      - name: commit-win32-x86_64
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update win32-x86_64 build artifacts"
          file_pattern: "*.rock manifest* index.html"
